
package org.bear.admin.service.rpc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ItemRpcServiceImplService", targetNamespace = "http://rpc.service.admin.bear.org/", wsdlLocation = "http://manage.xxkj.cn/rest/ws/itemService?wsdl")
public class ItemRpcServiceImplService
    extends Service
{

    private final static URL ITEMRPCSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMRPCSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ITEMRPCSERVICEIMPLSERVICE_QNAME = new QName("http://rpc.service.admin.bear.org/", "ItemRpcServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://manage.xxkj.cn/rest/ws/itemService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMRPCSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ITEMRPCSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ItemRpcServiceImplService() {
        super(__getWsdlLocation(), ITEMRPCSERVICEIMPLSERVICE_QNAME);
    }

    public ItemRpcServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMRPCSERVICEIMPLSERVICE_QNAME, features);
    }

    public ItemRpcServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ITEMRPCSERVICEIMPLSERVICE_QNAME);
    }

    public ItemRpcServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMRPCSERVICEIMPLSERVICE_QNAME, features);
    }

    public ItemRpcServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemRpcServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemRpcService
     */
    @WebEndpoint(name = "ItemRpcServiceImplPort")
    public ItemRpcService getItemRpcServiceImplPort() {
        return super.getPort(new QName("http://rpc.service.admin.bear.org/", "ItemRpcServiceImplPort"), ItemRpcService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemRpcService
     */
    @WebEndpoint(name = "ItemRpcServiceImplPort")
    public ItemRpcService getItemRpcServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rpc.service.admin.bear.org/", "ItemRpcServiceImplPort"), ItemRpcService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMRPCSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ITEMRPCSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ITEMRPCSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
