
package org.bear.admin.service.rpc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ItemRpcService", targetNamespace = "http://rpc.service.admin.bear.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItemRpcService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.bear.admin.service.rpc.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryItemById", targetNamespace = "http://rpc.service.admin.bear.org/", className = "org.bear.admin.service.rpc.QueryItemById")
    @ResponseWrapper(localName = "queryItemByIdResponse", targetNamespace = "http://rpc.service.admin.bear.org/", className = "org.bear.admin.service.rpc.QueryItemByIdResponse")
    public Item queryItemById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
